import path from "node:path";
import { fileURLToPath } from "node:url";
import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import viteReact from "@vitejs/plugin-react";
import { defineConfig } from "vite";

const rootDir = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
	plugins: [tailwindcss(), tanstackStart(), viteReact()],
	resolve: {
		tsconfigPaths: true,
		alias: {
			// `wasm/diff-wasm/pkg` is generated by `bun run build:wasm` and is
			// deliberately not a package.json dependency: a `file:` dependency breaks
			// `bun install` in toolchain-less environments and Renovate lockfile updates.
			"diff-wasm": path.resolve(rootDir, "./wasm/diff-wasm/pkg"),
		},
	},
	optimizeDeps: {
		exclude: ["diff-wasm"],
	},
	worker: {
		format: "es",
	},
});
