/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistryRouteRouteImport } from './routes/$registry/route'
import { Route as SpikeRouteImport } from './routes/spike'
import { Route as SpikeComboboxRouteImport } from './routes/spike-combobox'
import { Route as RegistryIndexRouteImport } from './routes/$registry/index'
import { Route as RegistrySplatRouteImport } from './routes/$registry/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRouteRoute = RegistryRouteRouteImport.update({
  id: '/$registry',
  path: '/$registry',
  getParentRoute: () => rootRouteImport,
} as any)
const SpikeRoute = SpikeRouteImport.update({
  id: '/spike',
  path: '/spike',
  getParentRoute: () => rootRouteImport,
} as any)
const SpikeComboboxRoute = SpikeComboboxRouteImport.update({
  id: '/spike-combobox',
  path: '/spike-combobox',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryIndexRoute = RegistryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegistryRouteRoute,
} as any)
const RegistrySplatRoute = RegistrySplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => RegistryRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$registry': typeof RegistryRouteRouteWithChildren
  '/spike': typeof SpikeRoute
  '/spike-combobox': typeof SpikeComboboxRoute
  '/$registry/$': typeof RegistrySplatRoute
  '/$registry/': typeof RegistryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spike': typeof SpikeRoute
  '/spike-combobox': typeof SpikeComboboxRoute
  '/$registry/$': typeof RegistrySplatRoute
  '/$registry': typeof RegistryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$registry': typeof RegistryRouteRouteWithChildren
  '/spike': typeof SpikeRoute
  '/spike-combobox': typeof SpikeComboboxRoute
  '/$registry/$': typeof RegistrySplatRoute
  '/$registry/': typeof RegistryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$registry'
    | '/spike'
    | '/spike-combobox'
    | '/$registry/$'
    | '/$registry/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/spike' | '/spike-combobox' | '/$registry/$' | '/$registry'
  id:
    | '__root__'
    | '/'
    | '/$registry'
    | '/spike'
    | '/spike-combobox'
    | '/$registry/$'
    | '/$registry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistryRouteRoute: typeof RegistryRouteRouteWithChildren
  SpikeRoute: typeof SpikeRoute
  SpikeComboboxRoute: typeof SpikeComboboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$registry': {
      id: '/$registry'
      path: '/$registry'
      fullPath: '/$registry'
      preLoaderRoute: typeof RegistryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spike': {
      id: '/spike'
      path: '/spike'
      fullPath: '/spike'
      preLoaderRoute: typeof SpikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spike-combobox': {
      id: '/spike-combobox'
      path: '/spike-combobox'
      fullPath: '/spike-combobox'
      preLoaderRoute: typeof SpikeComboboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$registry/': {
      id: '/$registry/'
      path: '/'
      fullPath: '/$registry/'
      preLoaderRoute: typeof RegistryIndexRouteImport
      parentRoute: typeof RegistryRouteRoute
    }
    '/$registry/$': {
      id: '/$registry/$'
      path: '/$'
      fullPath: '/$registry/$'
      preLoaderRoute: typeof RegistrySplatRouteImport
      parentRoute: typeof RegistryRouteRoute
    }
  }
}

interface RegistryRouteRouteChildren {
  RegistrySplatRoute: typeof RegistrySplatRoute
  RegistryIndexRoute: typeof RegistryIndexRoute
}

const RegistryRouteRouteChildren: RegistryRouteRouteChildren = {
  RegistrySplatRoute: RegistrySplatRoute,
  RegistryIndexRoute: RegistryIndexRoute,
}

const RegistryRouteRouteWithChildren = RegistryRouteRoute._addFileChildren(
  RegistryRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistryRouteRoute: RegistryRouteRouteWithChildren,
  SpikeRoute: SpikeRoute,
  SpikeComboboxRoute: SpikeComboboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
